config/routes.rb
Rails.application.routes.draw do

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#error", :code => code
  end

  get 'admin' => 'admin#root', as: :admin_login
  post 'admin' => 'admin#login'
  get 'admin/hackers' => 'admin#hackers', as: :admin_hackers
  get 'admin/mentors' => 'admin#mentors', as: :admin_mentors
  get 'admin/view/:id' => 'admin#view', as: :admin_view_user
  get 'admin/have_forms/:id' => 'admin#have_forms', as: :admin_have_forms
  get 'admin/emails.txt' => 'admin#all_emails'
  get 'admin/hacker_emails.txt' => 'admin#hacker_emails'
  get 'admin/mentor_emails.txt' => 'admin#mentor_emails'
  get 'admin/hackers_no_forms.txt' => 'admin#hackers_no_forms'
  get 'admin/mentors_no_forms.txt' => 'admin#mentors_no_forms'
  get 'admin/hackers_no_confirmation.txt' => 'admin#hackers_no_confirmation'
  get 'admin/mentors_no_confirmation.txt' => 'admin#mentors_no_confirmation'
  delete 'admin/sign_out' => 'admin#logout', as: :admin_logout

  devise_for :hackers, :skip => [:registrations, :sessions]
  devise_scope :hacker do
    post "sign_in" => "session#create", as: :hacker_session
    delete "sign_out" => "session#destroy", as: :destroy_hacker_session
    get "reset" => "reset#new", as: :start_password_reset
    post "reset" => "reset#create", as: :password_reset_lookup
    get "recover" => "reset#edit", as: :change_hacker_password
    post "recover" => "reset#update", as: :update_hacker_password
  end

  root "registration#home", as: :root
  get "/" => "registration#home", as: :new_hacker_session
  get "hacker/sign_up" => "registration#hacker_sign_up", as: :hacker_sign_up
  get "mentor/sign_up" => "registration#mentor_sign_up", as: :mentor_sign_up
  get "info" => "registration#info"
  get "status" => "registration#status"
  get "team" => "registration#team_view", as: :team

end

app/views/admin/_hacker.html.erb
<div class="ui divided items" id="user_data">
  <div class="item">
    <h1 class="image">
      School
    </h1>
    <div class="content">
      <div class="header">
        <%= hacker.school %>
      </div>
      <div class="meta">
        <%= hacker.year %>
      </div>
    </div>
  </div>
  <div class="item">
    <h1 class="image">
      Phone
    </h1>
    <div class="content">
      <div class="header">
        <%= phone(hacker) %>
      </div>
      <div class="meta">
        <%= get_state(hacker) %>
      </div>
    </div>
  </div>
  <div class="item">
    <h1 class="image">
      Interests
    </h1>
    <div class="content">
      <div class="description">
        <%= hacker.interests.join(", ") %>
      </div>
    </div>
  </div>
  <div class="item">
    <h1 class="image">
      Essay #1
    </h1>
    <div class="content">
      <div class="header">
        Describe your previous coding experience, if any.
      </div>
      <div class="description">
        <%= hacker.experience %>
      </div>
    </div>
  </div>
  <div class="item">
    <h1 class="image">
      Essay #2
    </h1>
    <div class="content">
      <div class="header">
        Why do you want to come to Blueprint?
      </div>
      <div class="description">
        <%= hacker.desire %>
      </div>
    </div>
  </div>
  <div class="item">
    <h1 class="image">
      Team
    </h1>
    <div class="content">
      <div class="description">
        <%= team(hacker) %>
      </div>
    </div>
  </div>
  <div class="item">
    <h1 class="image">
      Diet
    </h1>
    <div class="content">
      <div class="description">
        <%= hacker.dietary_restrictions %>
      </div>
    </div>
  </div>
  <div class="item">
    <h1 class="image">
      Joined
    </h1>
    <div class="content">
      <div class="description">
        <%= hacker.created_at.strftime("%B %d, %Y") %>
      </div>
    </div>
  </div>
  <div class="item">
  </div>
</div>

app/views/admin/_hacker_small.html.erb
<tr>
  <td><%= link_to hacker.name, admin_view_user_path(hacker.id), target: '_blank' %></td>
  <td><%= hacker.email %></td>
  <td>
    <% if hacker.status > 4 %>
    <i class="check icon"></i>
    <% end %>
  </td>
  <td>
    <% if hacker.attending_day1? %>
    <i class="check icon"></i>
    <% end %>
  </td>
  <td>
    <% if hacker.attending? %>
    <i class="check icon"></i>
    <% end %>
  </td>
  <td>
    <%= link_to ((hacker.have_forms?) ? "UNDO RECEIVE" : "Mark as received"), admin_have_forms_path(hacker) %>
  </td>
</tr>

app/views/admin/_mentor.html.erb
<div class="ui divided items" id="user_data">
  <div class="item">
    <h1 class="image">
      School
    </h1>
    <div class="content">
      <div class="header">
        <%= mentor.school %>
      </div>
      <div class="meta">
        <%= mentor.year %>
      </div>
    </div>
  </div>
  <div class="item">
    <h1 class="image">
      Phone
    </h1>
    <div class="content">
      <div class="header">
        <%= phone(mentor) %>
      </div>
      <div class="meta">
        <%= get_state(mentor) %>
      </div>
    </div>
  </div>
  <div class="item">
    <h1 class="image">
      Expertise
    </h1>
    <div class="content">
      <div class="description">
        <%= mentor.interests.join(", ") %>
      </div>
    </div>
  </div>
  <div class="item">
    <h1 class="image">
      Essay #1
    </h1>
    <div class="content">
      <div class="header">
        Describe your previous mentoring experience, if any.
      </div>
      <div class="description">
        <%= mentor.experience %>
      </div>
    </div>
  </div>
  <div class="item">
    <h1 class="image">
      Essay #2
    </h1>
    <div class="content">
      <div class="header">
        Why do you want to mentor at Blueprint?
      </div>
      <div class="description">
        <%= mentor.desire %>
      </div>
    </div>
  </div>
  <div class="item">
    <h1 class="image">
      Diet
    </h1>
    <div class="content">
      <div class="description">
        <%= mentor.dietary_restrictions %>
      </div>
    </div>
  </div>
  <div class="item">
    <h1 class="image">
      Joined
    </h1>
    <div class="content">
      <div class="description">
        <%= mentor.created_at.strftime("%B %d, %Y") %>
      </div>
    </div>
  </div>
  <div class="item">
  </div>
</div>

app/views/admin/_mentor_small.html.erb
<tr>
  <td><%= link_to mentor.name, admin_view_user_path(mentor.id), target: '_blank' %></td>
  <td><%= mentor.email %></td>
  <td>
    <% if mentor.status > 4 %>
    <i class="check icon"></i>
    <% end %>
  </td>
  <td>
    <% if mentor.attending_day1? %>
    <i class="check icon"></i>
    <% end %>
  </td>
  <td>
    <% if mentor.attending? %>
    <i class="check icon"></i>
    <% end %>
  </td>
  <td>
    <%= link_to ((mentor.have_forms?) ? "UNDO RECEIVE" : "Mark as received"), admin_have_forms_path(mentor) %>
  </td>
</tr>

app/views/admin/hackers.html.erb
<h1 class="ui center aligned icon header">
  <i class="circular users icon"></i>
  Hackers
</h1>

<div class="ui center aligned header">
  <%= link_to "View Mentors", admin_mentors_path, class: "ui button" %>
  <%= link_to "Log Out", admin_logout_path, method: :delete, class: "ui negative button" %>
</div>

<div class="ui centered aligned header">
  Total Records: <%= @hackers.length %>,
  Confirmed: <%= @hackers.where(status: 5..10000).length %>,
  Day 1: <%= @hackers.where(attending_day1: true).length %>,
  Day 2: <%= @hackers.where(attending: true).length %>,
  Forms: <%= @hackers.where(have_forms: true).length %>
</div>

<table class="ui table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Confirmed?</th>
      <th>Attending Day 1?</th>
      <th>Attending Day 2?</th>
      <th>Forms</th>
    </tr>
  </thead>
<% for hacker in @hackers %>
  <%= render partial: 'hacker_small', locals: { hacker: hacker } %>
<% end %>
</table>

app/views/admin/mentors.html.erb
<h1 class="ui center aligned icon header">
  <i class="circular meh icon"></i>
  Mentors
</h1>

<div class="ui center aligned header">
  <%= link_to "View Hackers", admin_hackers_path, class: "ui button" %>
  <%= link_to "Log Out", admin_logout_path, method: :delete, class: "ui negative button" %>
</div>

<div class="ui centered aligned header">
  Total Records: <%= @mentors.length %>,
  Confirmed: <%= @mentors.where(status: 5..10000).length %>,
  Day 1: <%= @mentors.where(attending_day1: true).length %>,
  Day 2: <%= @mentors.where(attending: true).length %>,
  Forms: <%= @mentors.where(have_forms: true).length %>
</div>

<table class="ui table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Confirmed?</th>
      <th>Attending Day 1?</th>
      <th>Attending Day 2?</th>
      <th>Forms</th>
    </tr>
  </thead>
<% for mentor in @mentors %>
  <%= render partial: 'mentor_small', locals: { mentor: mentor } %>
<% end %>
</table>

app/views/admin/root.html.erb
<h1 class="ui center aligned header">
  Admin Login
</h1>

<%= form_tag(admin_login_path, class: "ui form") do %>
  <div class="ui center aligned segment column">
    <div class="<%= "error " if flash[:error] %> field">
      <label>Login Key</label>
      <input placeholder="Login Key" name="key" id="login_key" type="text" />
    </div>
    <%= submit_tag "Log In", class: "ui button centered" %>
  </div>
<% end %>

app/views/admin/view.html.erb
<h1 class="ui center aligned icon header">
  <i class="circular user icon"></i>
  <%= @user.name %>
  <div class="sub header">
    <%= @user.email %>
  </div>
</h1>

<% if @user.mentor? %>
<%= render partial: 'mentor', locals: { mentor: @user } %>
<% else %>
<%= render partial: 'hacker', locals: { hacker: @user } %>
<% end %>